"""Accounting rules service — CRUD with eager-loaded entries."""

from __future__ import annotations

import re
from collections.abc import Mapping
from datetime import date
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from backend.models.accounting_rule import AccountingRule, AccountingRuleEntry
from backend.schemas.accounting_rule import AccountingRuleUpdate, RulePreviewEntry


async def list_rules(db: AsyncSession) -> list[AccountingRule]:
    result = await db.execute(
        select(AccountingRule)
        .options(selectinload(AccountingRule.entries))
        .order_by(AccountingRule.priority.asc(), AccountingRule.id.asc())
    )
    return list(result.scalars().all())


async def get_rule(db: AsyncSession, rule_id: int) -> AccountingRule | None:
    result = await db.execute(
        select(AccountingRule)
        .where(AccountingRule.id == rule_id)
        .options(selectinload(AccountingRule.entries))
    )
    return result.scalar_one_or_none()


async def update_rule(
    db: AsyncSession, rule: AccountingRule, payload: AccountingRuleUpdate
) -> AccountingRule:
    for field in ("name", "is_active", "priority", "description"):
        value = getattr(payload, field)
        if value is not None:
            setattr(rule, field, value)

    if payload.entries is not None:
        # Replace all rule entries
        for existing in list(rule.entries):
            await db.delete(existing)
        await db.flush()
        for entry_data in payload.entries:
            db.add(
                AccountingRuleEntry(
                    rule_id=rule.id,
                    account_number=entry_data.account_number,
                    side=entry_data.side,
                    description_template=entry_data.description_template,
                )
            )

    await db.commit()
    await db.refresh(rule)
    return rule


def _render_template(template: str, context: Mapping[str, object]) -> str:
    """Replace {{key}} placeholders in a template string with context values."""

    def replace(m: re.Match[str]) -> str:
        key = m.group(1).strip()
        return str(context.get(key, m.group(0)))

    return re.sub(r"\{\{(\w+)\}\}", replace, template)


async def preview_rule(
    db: AsyncSession,
    rule_id: int,
    amount: Decimal,
    label: str,
    entry_date: date | None = None,
) -> list[RulePreviewEntry] | None:
    """Simulate entries that would be generated by a rule, without DB writes.

    Returns None if the rule is not found.
    """
    rule = await get_rule(db, rule_id)
    if rule is None:
        return None

    ctx = {"label": label, "amount": str(amount)}
    result: list[RulePreviewEntry] = []
    for rule_entry in rule.entries:
        rendered_label = _render_template(rule_entry.description_template, ctx)
        debit = amount if rule_entry.side == "debit" else Decimal("0")
        credit = amount if rule_entry.side == "credit" else Decimal("0")
        result.append(
            RulePreviewEntry(
                account_number=rule_entry.account_number,
                label=rendered_label,
                debit=debit,
                credit=credit,
            )
        )
    return result
